### ISSUE TITLE
exculsion list!

### ISSUE THREAD

**Issue by amirgi73** [filovirid/simorgh#2]
I believe Exclusion list **isn't a good idea!** Instead, We should work on making the algorithm better so it creates less false positives! 
Using an Exclusion List is a messy work and websites listed there will be soon out of count!
I think An easy way to check if a website is a phishing one or not will be to check if the https certificate of the website is trustworthy or not?
Besides, having an whitelist is way simpler as number of those sites won't be more than 50!

**Comment by filovirid** [comment]
@Amirgi73,
Thanks for you comment.
The fact is that having an exclusion list is somehow a necessary part of every phishing detection system. For example, most of malware and phishing detection system try to whitelist the domain names in top 1 million Alexa ranking list (of course on server-side code not client side).
However, we do not need such a long list since the ranking system and domain popularity in our country is far different.
Some websites are not officially banking gateways but still have the very same features as banking systems (e.g., modern.ttbank.ir which is not an official gateways but in terms of characteristics, it's very similar to gateways). So, we need to exclude such domain names to reduce the False positive detection.
If you still not convinced, let me know.
Thanks
